import type { Movie } from "@/types/movie";

export const mockMovies: Movie[] = [
  {
    mobifliks_id: "mock-1",
    title: "The Dark Knight",
    year: 2008,
    language: "English",
    type: "movie",
    image_url: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    genres: ["Action", "Crime", "Drama"],
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    views: 125000,
  },
  {
    mobifliks_id: "mock-2",
    title: "Inception",
    year: 2010,
    language: "English",
    type: "movie",
    image_url: "https://image.tmdb.org/t/p/w500/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg",
    genres: ["Action", "Sci-Fi", "Thriller"],
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    views: 98000,
  },
  {
    mobifliks_id: "mock-3",
    title: "Interstellar",
    year: 2014,
    language: "English",
    type: "movie",
    image_url: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    genres: ["Adventure", "Drama", "Sci-Fi"],
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    views: 87000,
  },
  {
    mobifliks_id: "mock-4",
    title: "The Matrix",
    year: 1999,
    language: "English",
    type: "movie",
    image_url: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    genres: ["Action", "Sci-Fi"],
    description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    views: 156000,
  },
  {
    mobifliks_id: "mock-5",
    title: "Pulp Fiction",
    year: 1994,
    language: "English",
    type: "movie",
    image_url: "https://image.tmdb.org/t/p/w500/fIE3lAGcZDV1G6XM5KmuWnNsPp1.jpg",
    genres: ["Crime", "Drama"],
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    views: 112000,
  },
  {
    mobifliks_id: "mock-6",
    title: "Breaking Bad",
    year: 2008,
    language: "English",
    type: "series",
    image_url: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    genres: ["Crime", "Drama", "Thriller"],
    description: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine.",
    views: 245000,
  },
  {
    mobifliks_id: "mock-7",
    title: "Stranger Things",
    year: 2016,
    language: "English",
    type: "series",
    image_url: "https://image.tmdb.org/t/p/w500/x2LSRK2Cm7MZhjluni1msVJ3wDF.jpg",
    genres: ["Drama", "Fantasy", "Horror"],
    description: "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces.",
    views: 189000,
  },
  {
    mobifliks_id: "mock-8",
    title: "Game of Thrones",
    year: 2011,
    language: "English",
    type: "series",
    image_url: "https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    genres: ["Action", "Adventure", "Drama"],
    description: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns.",
    views: 320000,
  },
  {
    mobifliks_id: "mock-9",
    title: "The Shawshank Redemption",
    year: 1994,
    language: "English",
    type: "movie",
    image_url: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    genres: ["Drama"],
    description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    views: 178000,
  },
  {
    mobifliks_id: "mock-10",
    title: "Fight Club",
    year: 1999,
    language: "English",
    type: "movie",
    image_url: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    genres: ["Drama"],
    description: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club.",
    views: 134000,
  },
  {
    mobifliks_id: "mock-11",
    title: "The Godfather",
    year: 1972,
    language: "English",
    type: "movie",
    image_url: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    genres: ["Crime", "Drama"],
    description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    views: 267000,
  },
  {
    mobifliks_id: "mock-12",
    title: "Forrest Gump",
    year: 1994,
    language: "English",
    type: "movie",
    image_url: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    genres: ["Drama", "Romance"],
    description: "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other history unfold through the perspective of an Alabama man.",
    views: 198000,
  },
];

export const mockSeries: Movie[] = mockMovies.filter(m => m.type === "series");
export const mockTrending: Movie[] = mockMovies.slice(0, 8);
export const mockRecentMovies: Movie[] = mockMovies.filter(m => m.type === "movie");
export const mockPopularSearches: string[] = ["Action", "Comedy", "Horror", "Drama", "Sci-Fi", "Romance", "Thriller"];
